import { MessageCircle, Paperclip, Plus } from "lucide-react";

const columns = [
  { title: "Backlog", cards: [{ title: "Interview five workspace leads", label: "Research", owner: "NM" }, { title: "Define launch success metrics", label: "Strategy", owner: "AK" }] },
  { title: "Todo", cards: [{ title: "Write marketplace guidelines", label: "Content", owner: "LM" }, { title: "Prepare onboarding templates", label: "Product", owner: "AK" }] },
  { title: "In progress", cards: [{ title: "Build responsive navigation", label: "Engineering", owner: "TO", comments: 4 }, { title: "Refine opportunity cards", label: "Design", owner: "NM" }] },
  { title: "Done", cards: [{ title: "Map core user journeys", label: "Research", owner: "NM" }, { title: "Set product principles", label: "Strategy", owner: "AK" }] },
];

export function KanbanBoard() {
  return <div className="-mx-4 overflow-x-auto px-4 pb-4 sm:-mx-6 sm:px-6"><div className="grid min-w-[980px] grid-cols-4 gap-4">{columns.map((column) => <section key={column.title} className="rounded-xl bg-surface p-3"><div className="flex items-center justify-between px-1 pb-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-primary/60" /><h2 className="text-sm font-semibold text-secondary">{column.title}</h2><span className="text-xs text-muted-foreground">{column.cards.length}</span></div><button className="rounded-md p-1 text-muted-foreground hover:bg-muted"><Plus className="h-4 w-4" /></button></div><div className="space-y-3">{column.cards.map((card) => <article key={card.title} className="rounded-xl border border-border bg-card p-4 shadow-[0_1px_2px_color-mix(in_oklab,var(--secondary)_5%,transparent)] transition-all hover:-translate-y-0.5 hover:shadow-md"><span className="text-[10px] font-semibold uppercase tracking-wider text-primary">{card.label}</span><h3 className="mt-2 text-sm font-semibold leading-snug text-secondary">{card.title}</h3><div className="mt-5 flex items-center justify-between"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary-soft text-[10px] font-semibold text-primary">{card.owner}</span><span className="flex items-center gap-3 text-muted-foreground">{card.comments && <span className="flex items-center gap-1 text-xs"><MessageCircle className="h-3.5 w-3.5" />{card.comments}</span>}<Paperclip className="h-3.5 w-3.5" /></span></div></article>)}</div><button className="mt-3 flex w-full items-center gap-2 rounded-lg px-2 py-2 text-xs font-medium text-muted-foreground hover:bg-muted"><Plus className="h-3.5 w-3.5" /> Add item</button></section>)}</div></div>;
}