import { Link } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, MapPin, MoreHorizontal, Users } from "lucide-react";
import { KanbanBoard } from "./kanban-board";
import { PrimaryAction, ProductShell } from "./product-shell";
import { boards, members, opportunities } from "../data/product";

export function HomePage() { return <ProductShell title="Welcome to your office, Amara" eyebrow="Tuesday, 12 June"><section className="rounded-2xl border border-border bg-secondary p-6 text-secondary-foreground sm:p-8"><p className="text-sm text-secondary-foreground/60">Execution is visible</p><div className="mt-2 grid gap-6 md:grid-cols-[minmax(0,1fr)_auto] md:items-end"><div><h2 className="max-w-xl text-2xl font-semibold sm:text-3xl">Three things are moving forward today.</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-secondary-foreground/60">Your website launch is on track. Two applications need review, and Demo Day planning is ready for the team.</p></div><Link to="/workspace" className="flex items-center gap-2 text-sm font-semibold text-accent">Open office <ArrowRight className="h-4 w-4" /></Link></div></section><div className="mt-8 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><section><SectionHead title="Recent offices" link="View all" /><div className="mt-4 grid gap-3">{boards.slice(0,2).map((b) => <BoardRow key={b.name} board={b} />)}</div></section><section><SectionHead title="Discover" link="Marketplace" /><div className="mt-4 rounded-2xl border border-border bg-card p-5"><span className="text-xs font-semibold text-primary">{opportunities[0].type}</span><h3 className="mt-2 text-lg font-semibold text-secondary">{opportunities[0].title}</h3><p className="mt-1 text-sm text-muted-foreground">{opportunities[0].org} · {opportunities[0].location}</p><Link to="/opportunity/$opportunityId" params={{ opportunityId: opportunities[0].id }} className="mt-5 flex items-center gap-2 text-sm font-semibold text-primary">View opportunity <ArrowRight className="h-4 w-4" /></Link></div></section></div></ProductShell>; }

export function WorkspacesPage() { return <ProductShell title="My Offices" eyebrow="Your digital offices" action={<PrimaryAction to="/workspace/create">New office</PrimaryAction>}><div className="mb-8 max-w-2xl"><h2 className="text-2xl font-semibold text-secondary">Where execution is visible.</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Each office brings a team, activities, and opportunities into one focused place.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{["Acacia Studio", "Nia Founder Circle", "Open Cities Research"].map((name, i) => <Link key={name} to="/workspace" className="group rounded-2xl border border-border bg-card p-5 transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><div className={`grid h-11 w-11 place-items-center rounded-xl ${i === 0 ? "bg-primary text-primary-foreground" : "bg-primary-soft text-primary"} font-semibold`}>{name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><h2 className="mt-8 text-lg font-semibold text-secondary">{name}</h2><p className="mt-1 text-sm text-muted-foreground">{i + 2} boards · {i * 3 + 5} members</p><div className="mt-6 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span>Active today</span><ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></div></Link>)}</div></ProductShell>; }

export function WorkspaceOverview() { return <ProductShell title="Overview" action={<PrimaryAction to="/boards">Create board</PrimaryAction>}><section className="grid gap-4 sm:grid-cols-3">{[{label:"Boards",value:"3", icon:BriefcaseBusiness},{label:"Members",value:"8",icon:Users},{label:"Open opportunities",value:"2",icon:MapPin}].map(x=><div key={x.label} className="rounded-2xl border border-border bg-card p-5"><x.icon className="h-5 w-5 text-primary"/><p className="mt-6 text-3xl font-semibold text-secondary">{x.value}</p><p className="mt-1 text-sm text-muted-foreground">{x.label}</p></div>)}</section><div className="mt-8 grid gap-8 xl:grid-cols-[1.5fr_1fr]"><section><SectionHead title="Recent boards" link="View boards" /><div className="mt-4 space-y-3">{boards.map(b=><BoardRow key={b.name} board={b}/>)}</div></section><section><SectionHead title="Recent activity" /><div className="mt-4 rounded-2xl border border-border bg-card p-5">{["Nia moved a task to In progress","Tobi joined the workspace","Amara published an opportunity","Lerato added a Demo Day brief"].map((x,i)=><div key={x} className="flex gap-3 border-b border-border py-3 first:pt-0 last:border-0 last:pb-0"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-primary"/><div><p className="text-sm font-medium text-secondary">{x}</p><p className="mt-1 text-xs text-muted-foreground">{i+1}h ago</p></div></div>)}</div></section></div></ProductShell>; }

export function BoardsPage() { return <ProductShell title="Website launch" eyebrow="Activities · Project" action={<PrimaryAction>Add item</PrimaryAction>}><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-muted-foreground">What would you like to manage?</p><div className="mt-3 flex -space-x-2">{["AK","NM","TO"].map(x=><span key={x} className="grid h-8 w-8 place-items-center rounded-full border-2 border-background bg-primary-soft text-[10px] font-semibold text-primary">{x}</span>)}</div></div><button className="rounded-lg border border-border p-2 text-muted-foreground"><MoreHorizontal className="h-4 w-4"/></button></div><KanbanBoard /></ProductShell>; }

export function MarketplacePage() { return <ProductShell title="Marketplace" eyebrow="Discover work and teams"><div className="max-w-2xl"><h2 className="text-3xl font-semibold leading-tight text-secondary">Opportunities that lead somewhere.</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Browse jobs, tenders, partnerships, and volunteering opportunities. Apply and step directly into a workspace where the work happens.</p></div><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{["All","Opportunities","Tenders","Partnerships","Volunteers"].map((x,i)=><button key={x} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-medium ${i===0?"bg-secondary text-secondary-foreground":"border border-border bg-card text-muted-foreground"}`}>{x}</button>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2">{opportunities.map(o=><OpportunityCard key={o.id} item={o}/>)}</div></ProductShell>; }

export function MembersPage() { return <ProductShell title="Members" eyebrow="Acacia Studio" action={<PrimaryAction>Invite member</PrimaryAction>}><div className="max-w-xl"><h2 className="text-2xl font-semibold text-secondary">The people behind the work.</h2><p className="mt-2 text-sm text-muted-foreground">Roles and availability are visible without reducing people to rows.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{members.map(m=><article key={m.name} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-primary-soft font-semibold text-primary">{m.initials}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${m.availability==="Available"?"bg-primary-soft text-primary":"bg-muted text-muted-foreground"}`}>{m.availability}</span></div><h2 className="mt-5 text-base font-semibold text-secondary">{m.name}</h2><p className="mt-1 text-sm text-muted-foreground">{m.role}</p><div className="mt-5 border-t border-border pt-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Skills</p><p className="mt-1 text-sm text-secondary">{m.skills}</p></div></article>)}</div></ProductShell>; }

function SectionHead({title,link}:{title:string;link?:string}) { return <div className="flex items-center justify-between"><h2 className="text-base font-semibold text-secondary">{title}</h2>{link&&<span className="text-xs font-semibold text-primary">{link}</span>}</div>; }
function BoardRow({board}:{board:(typeof boards)[number]}) { return <Link to="/boards" className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 rounded-2xl border border-border bg-card p-4 transition-colors hover:bg-surface"><span className={`h-10 w-1 rounded-full ${board.color}`}/><span className="min-w-0"><span className="block truncate text-sm font-semibold text-secondary">{board.name}</span><span className="mt-1 block text-xs text-muted-foreground">{board.type} · {board.updated}</span><span className="mt-3 block h-1.5 overflow-hidden rounded-full bg-muted"><span className="block h-full rounded-full bg-primary" style={{width:`${board.progress}%`}}/></span></span><span className="text-xs font-semibold text-muted-foreground">{board.progress}%</span></Link>; }
function OpportunityCard({item}:{item:(typeof opportunities)[number]}) { return <article className="rounded-2xl border border-border bg-card p-5 transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-primary-soft px-3 py-1 text-[10px] font-semibold text-primary">{item.type}</span><button className="text-muted-foreground"><MoreHorizontal className="h-4 w-4"/></button></div><h2 className="mt-6 text-lg font-semibold text-secondary">{item.title}</h2><p className="mt-1 text-sm font-medium text-secondary">{item.org}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5"/>{item.location}</p><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-5 flex items-end justify-between gap-3"><div className="flex flex-wrap gap-1.5">{item.skills.map(s=><span key={s} className="rounded-md bg-muted px-2 py-1 text-[10px] text-muted-foreground">{s}</span>)}</div><Link to="/opportunity/$opportunityId" params={{ opportunityId:item.id }} className="shrink-0 text-sm font-semibold text-primary">View</Link></div></article>; }